### ISSUE TITLE
استفاده از ریئکت فقط در قسمتی از یک پیج

### ISSUE THREAD

**Issue by farhadmpr** [Ali-Doustkani/blog-examples#4]
<div dir='rtl'>

سلام

آیا امکانی وجود دارد که react را در قسمتی از یک razor پیج استفاده کنیم؟
به عنوان مثال اگر صفحه ای داشته باشیم که بخواهیم فقط در قسمت ساید بار آن لیست محصولات را با استفاده از react نمایش دهیم و بقیه صفحه در حالت عادی بماند
یعنی میخواهیم کاملا spa نداشته باشیم و ریئکت را در multi page application استفاده کنیم
در برخی از صفحات و آنهم در قسمتی از آن صفحات
خود صفحات razor باشند و سرور ساید

ممنون

</div>

**Comment by Ali-Doustkani** [comment]
سلام. مشکلی نداره. چون root element رو خودتون مشخص می کنید.

**Comment by Ali-Doustkani** [comment]
سلام. بله. در نهایت کل پروژه در یک المنت اچ تی ام ال قرار می گیره. برای ری اکت تفاوتی نداره که اون المنت کجاست

**Comment by farhadmpr** [comment]
در آنصورت چگونه باید به ریئکت بگوییم که مثلا اگر صفحه محصولات باز شد کامپیوننت لیست محصولات رندر بشه یا اگر صفحه دیگری باز شد کامپوننت مربوط به آن صفحه رندر شود؟

منظورم اینه که ما یک پروژه ریئک داریم که چند تا کامپوننت متفاوت داره و بر اساس اینکه چه صفحه ای از سرور ساید درخواست شود باید کامپوننت متناظر ریئکت در آن صفحه رندر شود

**Comment by Ali-Doustkani** [comment]
خلاصش می شه این
کامپوننت ری اکت جداگانه بیلد می شه و خروجیش مثل یه فایل جاوااسکریپت معمولی داخل صفحه ی محصولات استفاده می شه
یعنی ریزر ازش استفاده می کنه
حالا اینکه پروسه ی بیلد رو جچوری بچینید که برنامه نویسی به راحت ترین شکل انجام بشه دیگه هنر شماست

شاید برای این کار ابزارهایی هم باشه که من بی خبرم

فکر کنم محتوای این مقاله هم همین سوال شما بود، نبود؟

**Comment by farhadmpr** [comment]
دقیقا، ممنون
